### ISSUE TITLE
page link in title could not be seen

### ISSUE THREAD

**Issue by Phantato** [MatAmo93/logseq-atmos-theme#2]
Currently, the font color of link is the same as background of title. So if I use a link in title, it could not be seen.
Maybe we need to choose another color for such situation?

![image](https://github.com/Mat4m0/logseq-atmos-theme/assets/17043077/263f2dcb-13f8-48b5-a7b8-f2f4849189b8)
![image](https://github.com/Mat4m0/logseq-atmos-theme/assets/17043077/54bf06c1-8479-4414-835c-6acf261c475e)
![image](https://github.com/Mat4m0/logseq-atmos-theme/assets/17043077/6f3f138d-e18b-4b5b-bb7a-8fdcae9e9c0a)

**Comment by Mat4m0** [comment]
Fixed
